config/routes.rb
Rails.application.routes.draw do

  resources :translation_revisions

  resources :languages

  devise_for :users
  resources :users

  resources :project_users do
    member do
      post :create_project_user
    end
  end

  resources :projects do
    resources :project_languages
    resources :translation_entries do
      member do
        get :show_key
      end
      collection do
        get :search
      end
      resources :translations
    end
  end

  root 'home#index'

  namespace :api do
    namespace :v1 do
      resources :projects, :only => [:show, :update] do
        member do
          get :show_gettext
          patch :update_gettext
          put :update_gettext
        end
      end
    end
  end
end

app/models/translation_entry.rb
class TranslationEntry < ActiveRecord::Base
  enum key_type: [ :key, :block ]

  belongs_to :parent_entry, class_name: TranslationEntry
  belongs_to :project

  has_many :translations, dependent: :destroy

  before_save :generate_path

  def self.gettext
    where(gettext: true)
  end

  def self.yaml
    where.not(gettext: true)
  end

  private
  def generate_path
    if parent_entry
      prefix_path = "#{parent_entry.path}."
    else
      prefix_path = ""
    end
    self.path = "#{prefix_path}#{key}"
  end

end

app/controllers/translation_entries_controller.rb
class TranslationEntriesController < ApplicationController
  before_action :set_project
  before_action :set_translation_entry, only: [:show, :edit, :update, :destroy, :show_key]
  before_action :set_translation_keys, only: [:index, :show, :show_key]
  before_action :set_translations, except: [:search]
  before_action :set_parent_blocks, except: [:search]

  respond_to :html, :js

  def index
    #TODO: refactor
    #TODO: last updated ones
    # root_entry = @project.translation_entries.where(parent_entry_id: nil).first!
    @translation_entries = @project.translation_entries
                               .where(parent_entry_id: nil)
                               .order(:key_type => :desc, key: :asc).limit(30)
    render 'show'
  end

  def show
    #for directory listing
    @translation_entries = @project.translation_entries.where(parent_entry: @translation_entry).order(:key_type => :desc).all
    respond_with(@translation_entry)
  end

  def search
    query = ::TranslationEntryQuery.new(project: @project, search_keyword: params[:search_keyword])

    @translation_keys = query.results.includes(:translations).order('translation_entries.id ASC').order('translations.language_id ASC').limit(30)

    set_translations
    data = []
    @translations.each do |id, translations|
      data <<  {
        id: translations[0].translation_entry.id,
        path: translations[0].translation_entry.path,
        defaultLanguageTranslation: translations[0].value, # TODO: fix here
        defaultIsoCode: @project.default_language.iso_code,
        translations: translations
      }
    end
    render json: data.to_json
  end

  def show_key
    @translation_entry = @translation_entry.parent_entry
    @translation_entries = @project.translation_entries.where(parent_entry: @translation_entry).order(:key_type => :desc).all

    render 'show'
  end

  def new
    path = (TranslationEntry.find(params[:parent_entry_id]).path + '.') if params[:parent_entry_id]
    @translation_entry = TranslationEntry.new(path: path, key_type: params[:key_type])
    respond_with(@translation_entry)
  end

  def edit
  end

  def create
    action = Action::CreateTranslationEntry
                 .new(@project, translation_entry_params['path'], translation_entry_params['key_type'])
    @translation_entry = action.execute
    #TODO: action errors
    respond_with(@translation_entry)
  end

  def update
    @translation_entry.update(translation_entry_params)
    respond_with(@translation_entry)
  end

  def destroy
    @translation_entry.destroy
    respond_with(@translation_entry)
  end

  private

  def set_project
    @project = Project.find(params[:project_id])
  end

  def set_translation_entry
    @translation_entry = TranslationEntry.find(params[:id])
  end

  def translation_entry_params
    params.require(:translation_entry).permit(:path, :key_type)
  end

  def set_translation_keys
    #for translations
    if params[:action] == 'show_key'
      @translation_keys = [@translation_entry]
    else
      if @translation_entry
        @translation_keys = @project.translation_entries
                                .where(parent_entry: @translation_entry).key.includes(:translations).all
      else
        @translation_keys = []
      end
    end

  end

  def set_translations
    @translations = {}

    @translation_keys.try(:each) do |translation_key|
      missing_languages = @project.project_languages.where.not(language_id: translation_key.translations.select(:language_id))
      missing_languages.each do |missing_language|
          translation_key.translations.build(language: missing_language.language, value: '')
      end
      translation_key.save!
      @translations[translation_key.id] = translation_key.translations.where(language_id: @project.project_languages.pluck(:language_id))
        .joins(:language).select('translations.id, translations.translation_entry_id, translations.value, translations.language_id, languages.iso_code')
      #TODO: order by project language position
    end
  end

  def set_parent_blocks
    max_number_of_nesting = 10
    @parent_blocks = []
    if @translation_entry.present?
      block = @translation_entry.block? ? @translation_entry : @translation_entry.parent_entry
    end
    while !block.nil? && max_number_of_nesting > 0
      @parent_blocks << {block: block, siblings: TranslationEntry.where(parent_entry_id: block.parent_entry_id).block}
      block = block.parent_entry
      max_number_of_nesting -= 1
    end
    @parent_blocks.reverse!
  end
end

app/views/translation_entries/_add.html.haml
= link_to new_project_translation_entry_path(parent_entry_id: @translation_entry ? @translation_entry.id : nil, key_type: 'key'), remote: true, data: {toggle: 'modal', target: "#myModal"} do
  .btn.btn-primary.padder-v-lg.text-uppercase
    Add

app/views/translation_entries/_add_block.html.haml
= link_to new_project_translation_entry_path(parent_entry_id: @translation_entry ? @translation_entry.id : nil, key_type: 'block'), remote: true, data: {toggle: 'modal', target: "#myModal"} do
  .btn.btn-primary.padder-v-lg.text-uppercase
    Add Block

app/views/translation_entries/_directory.html.haml
.panel-body.no-border.file-list{ :style => "padding-top: 0" }
  .row.two-button
    .col-xs-3.bg-blue.text-center
      - if @translation_entry
        = link_to '', @translation_entry.parent_entry ? project_translation_entry_path(id: @translation_entry.parent_entry) : project_translation_entries_path,
           remote: true, class: 'directory-navigation-link glyphicon glyphicon-chevron-left text-white'
    .col-xs-9
      .dropdown.grey-dropdown.file-search
        %button#dropdownMenu1.btn.btn-grey.dropdown-toggle{"aria-expanded" => "true", "data-toggle" => "dropdown", :type => "button"}
          Dropdown
          %i.fa.fa-chevron-down
        %ul.dropdown-menu.dropdown-menu-left{"aria-labelledby" => "dropdownMenu1", :role => "menu"}
          %li{:role => "presentation"}
            %form{:role => "search"}
              .form-group
                %input.form-control{:placeholder => "Search", :type => "text"}/
          %li{:role => "presentation"}
            %a{:href => "#", :role => "menuitem", :tabindex => "-1"} File 1
          %li{:role => "presentation"}
            %a{:href => "#", :role => "menuitem", :tabindex => "-1"} File 2
          %li{:role => "presentation"}
            %a{:href => "#", :role => "menuitem", :tabindex => "-1"} File 3

.panel-body.no-padding.no-border.file-list
  %ul.list-group.no-border.file-list
    - @translation_entries.each do |translation_entry|
      %li.list-group-item.no-border{class: cycle('even', 'odd')}
        %i.fa.text-blue.marg-right-sm{class: translation_entry.block? ? 'fa-folder' : 'fa-file-text-o'}
        %span
          - if translation_entry.key?
            = link_to translation_entry.key, show_key_project_translation_entry_path(id: translation_entry), remote: true, class: 'directory-navigation-link text-black'
            -#= link_to translation_entry.key, project_translation_entry_translations_path(translation_entry_id: translation_entry), remote: true
          - else
            = link_to translation_entry.key, project_translation_entry_path(id: translation_entry), remote: true, class: 'directory-navigation-link text-black'
.text-center.marg-top
  = render partial: 'add_block'

app/views/translation_entries/_form.html.haml
= simple_form_for [@project, @translation_entry], remote: true do |f|
  = f.error_notification
  = f.input :key_type, as: :hidden

  .form-inputs
    = f.input :path, as: :string, input_html: { class: 'form-control' }

  %br
  .form-actions
    = f.button :submit, "#{modal_button(@translation_entry.key_type)}", class: 'pull-right btn btn-primary'
  %br
  %br

app/views/translation_entries/_keys.html.haml
#accordion.panel-group{"aria-multiselectable" => "true", :role => "tablist"}
  - @translation_keys.each_with_index do |translation_key, index|
    = render partial: 'translation_entry_accordion', locals: {translation_key: translation_key, index: index}

app/views/translation_entries/_translation_entry_accordion.html.haml
.panel.panel-default.no-border.no-border-radius
  #headingOne.panel-heading.padder-v{:role => "tab"}
    %h4.panel-title
      .row.two-button
        .col-xs-11.breadcrumbs-container
          %ol.breadcrumb.marg-none
            - @parent_blocks.each do |parent_block|
              %li
                = select_tag '', options_for_select(parent_block[:siblings].map{|s| [s.key, s.id, { class: "dictionary" }]}), selected: parent_block[:block].id
            %li.active.font-bold= translation_key.key
        .col-xs-1.text-center.bg-grey-light
          %a.text-black.font-bold.collapse-link{"aria-controls" => "collapseOne", "aria-expanded" => "true", "data-parent" => "#accordion", "data-toggle" => "collapse", :href => "#translation-#{translation_key.id}", :class => "#{index > 0 ? 'collapsed' : ''}"}

  .panel-collapse.collapse{"aria-labelledby" => "headingOne", :role => "tabpanel", :id => "translation-#{translation_key.id}", :class => "#{index == 0 ? 'in' : ''}"}
    - @translations[translation_key.id].each do |translation| #TODO: fix it
      .panel-body.no-border-radius.translation-container
        .row
          .col-xs-2.text-left.f16
            .flag{:class => "flag #{language_flag(translation.language.iso_code)}"}
            %h4.font-bold.text-uppercase.inline= translation.language.iso_code
          .col-xs-8
            .preview
              = link_to translation.value, '#', class: 'translation-editable', 'data-url' => project_translation_entry_translation_path(translation_entry_id: translation.translation_entry, id: translation)
          .col-xs-2.text-center
            %select.form-control.input-sm
              %option{:value => "1"} Completed
              %option{:value => "2"} Incomplete
              %option{:value => "3"} Revision

app/views/translation_entries/create.js.erb
<% if @translation_entry.block? %>
window.location = '<%= project_translation_entry_path(id: @translation_entry)%>';
<% else %>
window.location = '<%= show_key_project_translation_entry_path(id: @translation_entry)%>';
<% end %>

app/views/translation_entries/edit.html.haml
%h1 Editing translation_entry

= render 'form'

= link_to 'Show', @translation_entry
\|
= link_to 'Back', translation_entries_path

app/views/translation_entries/new.html.haml
%h1
  New translation_entry

= render 'form'

app/views/translation_entries/new.js.erb
<% if params[:key_type] == "key" %>
  $('#myModal .modal-title').html('Add new key');
<% else %>
  $('#myModal .modal-title').html('Add new block');
<% end %>
$('#myModal .modal-body').html("<%= j render("/translation_entries/form")%>");
$('#translation_entry_path').focus();

app/views/translation_entries/show.html.haml
= react_component('TranslationList', url: search_project_translation_entries_path(@current_user_projects.first),
         updateUrl: project_translation_entries_url(@current_user_projects.first))

app/views/translation_entries/show.js.erb
//TODO: loading
$('#translation_entries_directory_list').html("<%= j render("/translation_entries/directory")%>");
$('#add_button').html("<%= j render("/translation_entries/add")%>");
$('#translation_keys').html("<%= j render("/translation_entries/keys")%>");
initEditables();
initDirectoryNavigationLinks('.directory-navigation-link');