config/routes.rb
Rails.application.routes.draw do

  resources :translation_revisions

  resources :languages

  devise_for :users
  resources :users

  resources :project_users do
    member do
      post :create_project_user
    end
  end

  resources :projects do
    resources :project_languages
    resources :translation_entries do
      member do
        get :show_key
      end
      collection do
        get :search
      end
      resources :translations
    end
  end

  root 'home#index'

  namespace :api do
    namespace :v1 do
      resources :projects, :only => [:show, :update] do
        member do
          get :show_gettext
          patch :update_gettext
          put :update_gettext
        end
      end
    end
  end
end

app/models/translation.rb
class Translation < ActiveRecord::Base
  belongs_to :translation_entry
  belongs_to :language

  has_many :translation_revisions

  def create_translation_revision!(user)
    self.translation_revisions.create!(value: value, user: user)
  end
end

app/controllers/translations_controller.rb
class TranslationsController < ApplicationController
  before_action :set_translation_entry
  before_action :set_translation, only: [:show, :edit, :update, :destroy]

  respond_to :js

  def index
    @translations = @translation_entry.translations.all
    respond_with(@translations)
  end

  def show
    respond_with(@translation)
  end

  def new
    @translation = Translation.new
    respond_with(@translation)
  end

  def edit
  end

  def create
    @translation = Translation.new(translation_params)
    if @translation.save
      create_translation_revision
    end
    respond_with(@translation)
  end

  def update
    if @translation.update(translation_params_js)
      create_translation_revision
    end
    render text: @translation.errors.full_messages.join(',')
  end

  def destroy
    @translation.destroy
    respond_with(@translation)
  end

  private

  def set_translation_entry
    @translation_entry = TranslationEntry.find(params[:translation_entry_id])
  end

  def set_translation
    @translation = Translation.find(params[:id])
  end

  def translation_params
    params.require(:translation).permit(:translation_entry_id, :value, :language_id)
  end

  def translation_params_js
    params.permit(:translation_entry_id, :value, :language_id)
  end

  def create_translation_revision
    @translation.create_translation_revision!(current_user)
  end
end

app/helpers/translations_helper.rb
module TranslationsHelper
  def modal_button(key_type)
    key_type == 'key' ? 'Add key' : 'Add block'
  end
end

app/views/translations/_form.html.haml
= simple_form_for(@translation) do |f|
  = f.error_notification

  .form-inputs
    = f.association :translation_entry
    = f.input :value
    = f.association :language

  .form-actions
    = f.button :submit

app/views/translations/edit.html.haml
%h1 Editing translation

= render 'form'

= link_to 'Show', @translation
\|
= link_to 'Back', translations_path

app/views/translations/index.html.haml
%h1 Listing translations

- if @translation_entry && @translation_entry.parent_entry#TODO: fix it
  = link_to 'Back', project_translation_entry_path(id: @translation_entry.parent_entry)
.translations
  - @translations.each do |translation|
    .translation
      = simple_form_for translation, url: project_translation_entry_translation_path(id: translation) do |f|
        %span= f.object.language.name
        = f.input :value
        = f.submit
-#%table
-#  %thead
-#    %tr
-#      %th Translation entry
-#      %th Value
-#      %th Language
-#      %th
-#      %th
-#      %th
-#
-#  %tbody
-#    - @translations.each do |translation|
-#      %tr
-#        %td= translation.translation_entry
-#        %td= translation.value
-#        %td= translation.language
-#        -#%td= link_to 'Show', translation
-#        -#%td= link_to 'Edit', edit_translation_path(translation)
-#        -#%td= link_to 'Destroy', translation, :method => :delete, :data => { :confirm => 'Are you sure?' }
-#
-#%br
-#
-#-#= link_to 'New Translation', new_translation_path

app/views/translations/new.html.haml
%h1 New translation

= render 'form'

= link_to 'Back', translations_path

app/views/translations/show.html.haml
%p#notice= notice

%p
  %b Translation entry:
  = @translation.translation_entry
%p
  %b Value:
  = @translation.value
%p
  %b Language:
  = @translation.language

= link_to 'Edit', edit_translation_path(@translation)
\|
= link_to 'Back', translations_path