config/routes.rb
Rails.application.routes.draw do

  resources :translation_revisions

  resources :languages

  devise_for :users
  resources :users

  resources :project_users do
    member do
      post :create_project_user
    end
  end

  resources :projects do
    resources :project_languages
    resources :translation_entries do
      member do
        get :show_key
      end
      collection do
        get :search
      end
      resources :translations
    end
  end

  root 'home#index'

  namespace :api do
    namespace :v1 do
      resources :projects, :only => [:show, :update] do
        member do
          get :show_gettext
          patch :update_gettext
          put :update_gettext
        end
      end
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @projects = @current_user_projects
  end
end

app/views/home/_project.html.haml
.row
  .col-xs-4.text-center.bg-primary
    = link_to '#', :data => {:toggle => 'tooltip', :'original-title' => 'Users'} do
      Users
      = "#{project.users.count}"
  .col-xs-4.text-center.bg-danger
    = link_to project_project_languages_path(project), :remote => true, :data => {toggle: 'modal', target: '#myModal'} do
      Languages
      = "#{project.project_languages.count}"
  .col-xs-4.text-center.bg-success
    = link_to project_translation_entries_path(project), :data => {:toggle => 'tooltip', :'original-title' => 'Translation entries'} do
      Translations
      = "#{project.translation_entries.count}"

app/views/home/index.html.haml
.row
  .col-lg-12
    %h1.text-center.marg-bot-xl
      Projects
      =link_to new_project_path, remote: true, data: {toggle: 'modal', target: '#myModal'}, :class => 'btn btn-default' do
        Add new
        %i.fa.fa-plus
- @current_user_projects.in_groups_of(3, false).each do |group|
  .flex-container
    - group.each do |project|
      .flex-item.project-panel
        %h3.text-center.font-semibold
          = link_to project.name, project_translation_entries_path(project)
        %h5.text-left.marg-bot-xl
          = project.description
        .panel-body
          .row
            .col-xs-12.text-center.text-black
              API key
              = project.session_api_key.access_token
        .panel-footer
          = render partial: 'project', locals: {project: project}