config/routes.rb
Rails.application.routes.draw do

  resources :translation_revisions

  resources :languages

  devise_for :users
  resources :users

  resources :project_users do
    member do
      post :create_project_user
    end
  end

  resources :projects do
    resources :project_languages
    resources :translation_entries do
      member do
        get :show_key
      end
      collection do
        get :search
      end
      resources :translations
    end
  end

  root 'home#index'

  namespace :api do
    namespace :v1 do
      resources :projects, :only => [:show, :update] do
        member do
          get :show_gettext
          patch :update_gettext
          put :update_gettext
        end
      end
    end
  end
end

app/models/translation_revision.rb
class TranslationRevision < ActiveRecord::Base
  belongs_to :translation
  belongs_to :user
end

app/controllers/translation_revisions_controller.rb
class TranslationRevisionsController < ApplicationController
  before_action :set_translation_revision, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @translation_revisions = TranslationRevision.all
    respond_with(@translation_revisions)
  end

  def show
    respond_with(@translation_revision)
  end

  def new
    @translation_revision = TranslationRevision.new
    respond_with(@translation_revision)
  end

  def edit
  end

  def create
    @translation_revision = TranslationRevision.new(translation_revision_params)
    @translation_revision.save
    respond_with(@translation_revision)
  end

  def update
    @translation_revision.update(translation_revision_params)
    respond_with(@translation_revision)
  end

  def destroy
    @translation_revision.destroy
    respond_with(@translation_revision)
  end

  private

  def set_translation_revision
    @translation_revision = TranslationRevision.find(params[:id])
  end

  def translation_revision_params
    params.require(:translation_revision).permit(:translation_id, :user_id, :value)
  end
end

app/views/translation_revisions/_form.html.haml
= simple_form_for(@translation_revision) do |f|
  = f.error_notification

  .form-inputs
    = f.association :translation
    = f.association :user
    = f.input :value

  .form-actions
    = f.button :submit

app/views/translation_revisions/edit.html.haml
%h1 Editing translation_revision

= render 'form'

= link_to 'Show', @translation_revision
\|
= link_to 'Back', translation_revisions_path

app/views/translation_revisions/index.html.haml
%h1 Listing translation_revisions

%table
  %thead
    %tr
      %th Translation
      %th User
      %th Value
      %th
      %th
      %th
      
  %tbody
    - @translation_revisions.each do |translation_revision|
      %tr
        %td= translation_revision.translation
        %td= translation_revision.user
        %td= translation_revision.value
        %td= link_to 'Show', translation_revision
        %td= link_to 'Edit', edit_translation_revision_path(translation_revision)
        %td= link_to 'Destroy', translation_revision, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Translation revision', new_translation_revision_path

app/views/translation_revisions/new.html.haml
%h1 New translation_revision

= render 'form'

= link_to 'Back', translation_revisions_path

app/views/translation_revisions/show.html.haml
%p#notice= notice

%p
  %b Translation:
  = @translation_revision.translation
%p
  %b User:
  = @translation_revision.user
%p
  %b Value:
  = @translation_revision.value

= link_to 'Edit', edit_translation_revision_path(@translation_revision)
\|
= link_to 'Back', translation_revisions_path